package com.dbjina.schooltimer;

public enum FieldEnum {
	START_HOUR,
	START_MIN,
	MORNING_SUBJECT_COUNT,
	AFTERNOON_SUBJECT_COUNT,
	STUDYING_HOUR,
	STUDYING_MIN,
	BREAKING_TIME,
	LUNCH_HOUR,
	LUNCH_MIN,
	DINNER_HOUR,
	DINNER_MIN,
	BREAKING_BELL,
	MEAL_BELL
}
